# 图像去噪任务配置文件
task: "denoising"
version: "1.0"
description: "Image denoising configuration for DnCNN"

# 模型配置
model:
  name: "DnCNN"
  noise_level: 25
  checkpoint_path: "models/denoising/dncnn_25.pth"
  
  # 模型参数
  parameters:
    depth: 17
    num_channels: 64
    kernel_size: 3
    use_bnorm: true
    
# 输入配置
input:
  image_path: "data/input/"
  supported_formats: [".jpg", ".jpeg", ".png", ".bmp"]
  
  # 预处理
  preprocessing:
    normalize: true
    to_ycbcr: false
    
# 输出配置
output:
  save_path: "data/output/denoising/"
  format: "png"
  quality: 95
  
# 处理配置
processing:
  device: "cuda"
  batch_size: 4
  use_fp16: true
  
  # 分块处理
  patch_processing:
    enable: true
    patch_size: 256
    overlap: 32
    
# 验证配置
validation:
  enable: true
  metrics: ["PSNR", "SSIM"]
  
# 日志配置
logging:
  level: "INFO"
  save_path: "logs/denoising.log"