# 超分辨率任务配置文件
task: "super_resolution"
version: "1.0"
description: "Super-resolution configuration for ESRGAN"

# 模型配置
model:
  name: "ESRGAN"
  scale_factor: 4
  checkpoint_path: "models/super_resolution/esrgan_x4.pth"
  
  # 模型参数
  parameters:
    num_feat: 64
    num_block: 23
    num_grow_ch: 32
    
# 输入配置
input:
  image_path: "data/input/"
  supported_formats: [".jpg", ".jpeg", ".png", ".bmp"]
  
  # 预处理
  preprocessing:
    normalize: true
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    
# 输出配置
output:
  save_path: "data/output/super_resolution/"
  format: "png"
  quality: 95
  
# 处理配置
processing:
  device: "cuda"  # cuda/cpu
  batch_size: 1
  use_fp16: true
  
  # 内存优化
  memory_optimization:
    enable: true
    max_image_size: 2048
    tile_size: 512
    tile_overlap: 32
    
# 日志配置
logging:
  level: "INFO"
  save_path: "logs/super_resolution.log"